/**
 * BEXO Standard Preview Profile Data — Design & Creative
 * Default local preview data consumed when window.__BEXO_PROFILE__ is not injected.
 */

export const defaultProfile = {
  user: {
    name: 'Alex Mercer',
    firstName: 'Alex',
    lastName: 'Mercer',
    initials: 'AM',
    email: 'hello@alexmercer.design',
    phone: '+1 (555) 234-8901',
    photoUrl: 'assets/portrait.png',
    resumeUrl: 'assets/Alex_Mercer_Creative_Resume.pdf',
    openToHire: true,
    location: 'New York, NY',
    socials: [
      { label: 'LinkedIn', href: 'https://linkedin.com', icon: 'linkedin' },
      { label: 'Dribbble', href: 'https://dribbble.com', icon: 'dribbble' },
      { label: 'Behance', href: 'https://behance.net', icon: 'behance' },
      { label: 'Instagram', href: 'https://instagram.com', icon: 'instagram' },
    ],
  },
  profile: {
    handle: 'alexmercer',
    headline: 'Creative Director & Designer',
    careerGoal: 'Crafting unforgettable visual identities, high-impact design systems, and immersive digital narratives.',
    bio: 'Based in New York, I am a multidisciplinary Creative Director and Designer with over a decade of experience shaping the brand systems and digital products of high-growth technology and cultural companies.',
    tagline: 'Art Director & Interactive Designer',
    overviewQuote: 'Where visionary aesthetics meet rigorous digital craft.',
    heroStats: [
      { value: '10+', label: 'Years Experience', desc: 'Brand & digital systems' },
      { value: '45+', label: 'Delivered Projects', desc: 'From branding to WebGL' },
      { value: '14', label: 'Design Awards', desc: 'D&AD, Awwwards, AIGA' },
      { value: '250k+', label: 'Daily Users Impacted', desc: 'Across active platforms' },
    ],
  },
  projectEntries: [
    {
      id: 'cosmos-space',
      title: 'Cosmos Space Travel',
      category: 'Brand Experience & Spatial',
      year: '2026',
      role: 'Creative Director & Lead Designer',
      description: 'End-to-end luxury identity and spatial visual installation for an aerospace hospitality pioneer. Blended deep-space orbital mechanics with minimalist haute-luxe typography.',
      stack: ['Brand Identity', 'Motion Direction', 'Spatial Design', 'Editorial'],
      image: 'https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?w=1200&q=85',
      externalUrl: 'https://cosmos-luxury.space',
      featured: true,
      caseStudy: {
        statement: 'Designing the future of luxury travel — one constellation at a time.',
        challenge: 'Cosmos needed an identity that felt celestial yet grounded, living seamlessly across spacecraft livery, titanium membership tokens, and digital reservation suites.',
        solution: 'Developed an adaptive orbital grid and bespoke typographic glyphs inspired by celestial navigation charts.',
        metrics: [
          { label: 'Global Press Mentions', value: '120+' },
          { label: 'Waitlist Registrations', value: '45,000' },
          { label: 'Design Distinction', value: 'D&AD Yellow Pencil' },
        ],
        gallery: [
          'https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?w=1200&q=85',
          'https://images.unsplash.com/photo-1484600899469-230e8d1d59c0?w=1200&q=85',
          'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=1200&q=85',
        ],
      },
    },
    {
      id: 'flux-systems',
      title: 'Flux Collaboration Platform',
      category: 'Digital Product & UI/UX',
      year: '2026',
      role: 'Principal Product Designer',
      description: 'Unified collaborative canvas platform used by over 200,000 product teams globally. Focused on high-density data canvas interaction, spatial canvas tools, and instantaneous state synchronization.',
      stack: ['UI/UX Architecture', 'Design System', 'Prototyping', 'Interaction Design'],
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85',
      externalUrl: 'https://flux-systems.app',
      featured: true,
      caseStudy: {
        statement: 'Rethinking real-time collaboration for the next generation of creative teams.',
        challenge: 'High latency and UI clutter caused creative friction in complex multi-layer design reviews.',
        solution: 'Built a zero-latency spatial canvas paradigm with tactile micro-interactions and dark-mode ergonomics.',
        metrics: [
          { label: 'Daily Active Designers', value: '200,000+' },
          { label: 'User Satisfaction', value: '98.4%' },
          { label: 'Task Latency Reduction', value: '38%' },
        ],
        gallery: [
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85',
          'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&q=85',
          'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=1200&q=85',
        ],
      },
    },
    {
      id: 'atlas-broadcast',
      title: 'Atlas Nature Series',
      category: 'Motion Identity & Broadcast',
      year: '2025',
      role: 'Motion Director',
      description: 'Kinetic broadcast packaging, generative episode titles, and sound-reactive motion language for a flagship multi-part documentary series broadcast in 48 territories.',
      stack: ['Motion Design', 'After Effects', 'Cinema 4D', 'Sound Reactive'],
      image: 'https://images.unsplash.com/photo-1511376979163-f804dff7ad7b?w=1200&q=85',
      externalUrl: 'https://bbcstudios.com',
      featured: true,
      caseStudy: {
        statement: 'Motion as living narrative — an identity system that breathes.',
        challenge: 'Broadcasting across diverse cultures required a universal visual language that communicated wonder without subtitles.',
        solution: 'Engineered an organic waveform animation framework mirroring natural planetary frequencies.',
        metrics: [
          { label: 'Global Viewers', value: '28 Million' },
          { label: 'Territories Broadcast', value: '48' },
          { label: 'Industry Honors', value: 'BAFTA Nominated' },
        ],
        gallery: [
          'https://images.unsplash.com/photo-1511376979163-f804dff7ad7b?w=1200&q=85',
          'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=85',
          'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&q=85',
        ],
      },
    },
    {
      id: 'prism-webgl',
      title: 'Prism Generative Art Lab',
      category: 'Creative Technology & WebGL',
      year: '2025',
      role: 'Creative Technologist',
      description: 'Interactive browser-based WebGL audio-reactive laboratory demonstrating generative algorithmic art. Each visitor generates a mathematically unique digital sculpture.',
      stack: ['WebGL', 'Three.js', 'Custom GLSL Shaders', 'Web Audio API'],
      image: 'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=1200&q=85',
      externalUrl: 'https://artblock.io',
      featured: false,
      caseStudy: {
        statement: 'Where mathematical precision transforms into emotional art.',
        challenge: 'Rendering 60 FPS real-time fluid raymarching in standard mobile browsers without battery drain.',
        solution: 'Wrote bespoke WebGL fragment shaders with dynamic level-of-detail throttling based on hardware capability.',
        metrics: [
          { label: 'Unique Artworks Generated', value: '94,000+' },
          { label: 'Average Session Duration', value: '4m 32s' },
          { label: 'Awwwards Recognition', value: 'Site of the Day' },
        ],
        gallery: [
          'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=1200&q=85',
          'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=1200&q=85',
        ],
      },
    },
    {
      id: 'nomad-magazine',
      title: 'Nomad Editorial Journal',
      category: 'Editorial Direction & Print',
      year: '2024',
      role: 'Art Director & Photographer',
      description: 'Art direction, bespoke typography layout, and documentary photography for a bi-annual hardcover publication exploring remote architecture and solitary landscapes.',
      stack: ['Art Direction', 'Editorial Typography', 'Print Production', 'Photography'],
      image: 'https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?w=1200&q=85',
      externalUrl: 'https://nomadmag.co',
      featured: false,
      caseStudy: {
        statement: 'Documenting the stillness of uncharted terrain with raw documentary clarity.',
        challenge: 'Balancing archival typography with high-impact photographic spreads on tactile unbleached paper.',
        solution: 'Custom serif headline pairings with generous margins and bespoke metallic duotone plates.',
        metrics: [
          { label: 'Print Run Sold Out', value: '50,000 Copies' },
          { label: 'Featured In', value: 'AIGA Eye on Design' },
          { label: 'Award', value: 'TDC Certificate of Typographic Excellence' },
        ],
        gallery: [
          'https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?w=1200&q=85',
          'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=85',
        ],
      },
    },
  ],
  experienceEntries: [
    {
      role: 'Creative Director',
      company: 'Studio Volta',
      location: 'New York, NY',
      period: '2024 — Present',
      description: 'Lead agency creative direction across luxury technology, aerospace, and spatial design accounts. Mentor 18 multidisciplinary designers, 3D artists, and creative technologists.',
      highlights: [
        'Directed global brand campaigns with an aggregate client valuation over $12B.',
        'Established proprietary generative design system reducing creative production time by 35%.',
        'Won 4 international creative awards including D&AD Yellow Pencil 2026.',
      ],
    },
    {
      role: 'Senior Product Designer',
      company: 'Linear',
      location: 'San Francisco / Remote',
      period: '2021 — 2024',
      description: 'Designed core desktop and mobile product workflows for developer tools. Spearheaded dark-mode ergonomics, high-density keyboard shortcut navigation, and design token libraries.',
      highlights: [
        'Owned end-to-end design for project roadmap modules utilized by 250k+ daily users.',
        'Crafted micro-interaction feedback loops praised across design community forums.',
      ],
    },
    {
      role: 'Lead UX Designer',
      company: 'Figma',
      location: 'San Francisco, CA',
      period: '2019 — 2021',
      description: 'Developed advanced prototyping interactions, spatial canvas tools, and developer handoff capabilities.',
      highlights: [
        'Co-architected vector path rendering interface upgrades.',
        'Facilitated co-design workshops with design leadership at Apple, Stripe, and Airbnb.',
      ],
    },
    {
      role: 'Visual Designer',
      company: 'Pentagram Design',
      location: 'New York, NY',
      period: '2017 — 2019',
      description: 'Crafted identity systems, bespoke typographic guidelines, and environmental signage for cultural institutions, museums, and premier publishing houses.',
      highlights: [
        'Contributed to 6 major museum and exhibition identity rebranding launches.',
        'Published in Type Directors Club Annual and Print Magazine.',
      ],
    },
  ],
  educationEntries: [
    {
      degree: 'Master of Fine Arts (MFA) in Graphic & Interactive Design',
      institution: 'Rhode Island School of Design (RISD)',
      location: 'Providence, RI',
      year: '2017',
      honors: 'Summa Cum Laude • RISD Graduate Fellowship',
      description: 'Thesis focused on algorithmic motion systems and responsive typographic architecture.',
    },
    {
      degree: 'Bachelor of Arts (BA) in Visual Communication',
      institution: 'Parsons School of Design',
      location: 'New York, NY',
      year: '2015',
      honors: 'Dean’s Honor Scholar',
      description: 'Comprehensive foundation in editorial design, typography history, and interactive media.',
    },
  ],
  certificateEntries: [
    {
      name: 'Creative Direction in Spatial Computing',
      issuer: 'MIT Media Lab / Spatial Lab',
      year: '2025',
      credentialId: 'MIT-SPATIAL-8891',
      url: 'https://media.mit.edu',
    },
    {
      name: 'Advanced WebGL & Shaders Certification',
      issuer: 'Three.js Journey / Bruno Simon',
      year: '2024',
      credentialId: 'THREEJS-CERT-4412',
      url: 'https://threejs-journey.com',
    },
    {
      name: 'Executive Design Leadership',
      issuer: 'Stanford d.school',
      year: '2023',
      credentialId: 'STANFORD-DSCHOOL-092',
      url: 'https://dschool.stanford.edu',
    },
  ],
  achievementEntries: [
    {
      title: 'D&AD Yellow Pencil 2026',
      organization: 'D&AD Global Awards',
      year: '2026',
      description: 'Bestowed in Digital Design & Spatial Experience for Cosmos Space Travel brand identity.',
    },
    {
      title: 'Awwwards Site of the Year Nominee',
      organization: 'Awwwards International Jury',
      year: '2025',
      description: 'Recognized for technical excellence and artistic innovation in WebGL creative coding.',
    },
    {
      title: 'AIGA Eye on Design Distinction',
      organization: 'American Institute of Graphic Arts',
      year: '2025',
      description: 'Selected as one of the 10 most influential editorial publications of the year for Nomad Journal.',
    },
    {
      title: 'TDC Certificate of Typographic Excellence',
      organization: 'Type Directors Club New York',
      year: '2024',
      description: 'Awarded for bespoke display typography design and variable font mastery.',
    },
  ],
  researchEntries: [
    {
      title: 'Sub-Pixel Ergonomics in Dark-Mode Professional Tooling',
      publication: 'ACM SIGCHI Proceedings on Human-Computer Interaction',
      year: '2025',
      coAuthors: 'Alex Mercer, Dr. Elena Rostova',
      summary: 'Investigating chromatic aberration, luminance ratios, and ocular fatigue in high-density creative workstations.',
      link: 'https://dl.acm.org',
    },
    {
      title: 'Generative Typography: Real-Time Vector Tessellation via WebGL',
      publication: 'Journal of Digital Typography & Computation',
      year: '2024',
      coAuthors: 'Alex Mercer',
      summary: 'A novel algorithmic framework for fluid-state typographic deformation driven by audio telemetry and user proximity.',
      link: 'https://typography.org/journal',
    },
  ],
  skillEntries: [
    {
      category: 'Creative Direction & Strategy',
      skills: ['Brand Identity Systems', 'Design Systems Architecture', 'Editorial Art Direction', 'Spatial Design', 'Design Leadership', 'Typography Mastery'],
    },
    {
      category: 'UI/UX & Product Design',
      skills: ['Figma', 'High-Fidelity Prototyping', 'User Research & Journey Mapping', 'Design Ergonomics', 'Micro-interactions', 'Design Tokens'],
    },
    {
      category: 'Motion & 3D Spatial',
      skills: ['After Effects', 'Cinema 4D', 'Blender', 'Octane Render', 'Character & Kinetic Motion', 'Audio-Reactive Systems'],
    },
    {
      category: 'Creative Technology',
      skills: ['Three.js', 'WebGL & GLSL Shaders', 'HTML5 / CSS3 / Vanilla JS', 'Interactive Canvas', 'Creative Coding', 'Design-to-Code Engineering'],
    },
  ],
  services: [
    {
      number: '01',
      title: 'Brand Identity Systems',
      description: 'From primary mark to multi-surface design language, craft timeless brands that command attention.',
    },
    {
      number: '02',
      title: 'Digital Product & UI/UX',
      description: 'High-density web and mobile applications with intuitive ergonomics and obsessive craft.',
    },
    {
      number: '03',
      title: 'Motion & 3D Direction',
      description: 'Kinetic broadcast packaging, cinematic 3D renders, and living brand motion systems.',
    },
    {
      number: '04',
      title: 'Creative Technology & WebGL',
      description: 'Immersive browser experiences, custom shaders, and interactive audio-reactive installations.',
    },
  ],
  awards: [
    { year: '2026', title: 'D&AD Yellow Pencil', category: 'Digital Design' },
    { year: '2025', title: 'Awwwards Site of the Year Nominee', category: 'Creative Development' },
    { year: '2025', title: 'AIGA Eye on Design', category: 'Editorial' },
    { year: '2024', title: 'CSS Design Awards', category: 'Motion & Interaction' },
    { year: '2024', title: 'Type Directors Club', category: 'Typography' },
  ],
  clients: [
    { name: 'Apple' },
    { name: 'Spotify' },
    { name: 'Figma' },
    { name: 'Linear' },
    { name: 'BBC Studios' },
    { name: 'Pentagram' },
    { name: 'Nike' },
    { name: 'Artblock' },
  ],
};
